# Site settings
title: "Commented"
email: sherminn@piratefsh.net
description: "A blog by Sher Minn. Intersections of computer, history, and art."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://piratefsh.github.io" # the base hostname & protocol for your site
twitter_username: piratefsh
github_username:  piratefsh
paginate: 8
# Build settings
markdown: kramdown

gems:
    - jekyll-feed
    - jekyll-paginate
