# Site settings
title: "Commented"
email: sherminn.chong@gmail.com
description: > 
    A small blog on stuff that I like. May include front-end web development experiments, UI/UX design learnings and tea.
    I also co-run Code Equality where we organize local coding classes and events.
    This site is a work in progress on the default Jekyll template.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://piratefsh.github.io" # the base hostname & protocol for your site
twitter_username: piratefsh
github_username:  piratefsh

# Build settings
markdown: kramdown
